version: "3.3"
services:
  asa-server:
    container_name: asa-server
    hostname: asa-server
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:latest"
    environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -NoBattlEye -mods=929868
      - ENABLE_DEBUG=0
    ports:
      # Game port for player connections through the server browser
      - 0.0.0.0:7777:7777/udp
      # RCON port for remote server administration
      - 0.0.0.0:27020:27020/tcp
    depends_on:
      - set-permissions
    volumes:
      - steam:/home/gameserver/Steam:rw
      - steamcmd:/home/gameserver/steamcmd:rw
      - server-files:/home/gameserver/server-files:rw
      - ./root/usr/bin/start_server:/usr/bin/start_server:ro
      - type: bind
        source: $HOME/.local/share/asa-server/saved/
        target: /home/gameserver/saved/
        read_only: false
        bind:
          create_host_path: false
    networks:
      asa-network:
  set-permissions:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files'"
    user: root
    image: "opensuse/leap"
    volumes:
      - steam:/steam:rw
      - steamcmd:/steamcmd:rw
      - server-files:/server-files:rw
volumes:
  steam:
  steamcmd:
  server-files:
networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'
